change code scan

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -12,60 +12,62 @@ on:
 permissions: read-all
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "scan"
-  CodeScan:
-    permissions:
-      contents: read # for actions/checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-      
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
-      - uses: actions/checkout@v3
-
-      - name: Checkov GitHub Action
-        uses: bridgecrewio/checkov-action@v12
-        with:
-          # This will add both a CLI output to the console and create a results.sarif file
-          output_format: cli,sarif
-          output_file_path: console,results.sarif
+  job1:
+    # This workflow contains a single job called "scan"
+    CodeScan:
+      permissions:
+        contents: read # for actions/checkout to fetch code
+        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
         
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v3
-        
-        # Results are generated only on a success or failure
-        # this is required since GitHub by default won't run the next step
-        # when the previous one has failed. Security checks that do not pass will 'fail'.
-        # An alternative is to add `continue-on-error: true` to the previous step
-        # Or 'soft_fail: true' to checkov.
-        if: success() || failure()
-        with:
-          sarif_file: results.sarif
-jobs:
-  terraform:
-    runs-on: ubuntu-latest
+      # The type of runner that the job will run on
+      runs-on: ubuntu-latest
 
-    env:
-      ARM_CLIENT_ID: "04684342-05fe-44a5-9c41-176278bf7fbd"
-      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
-      ARM_SUBSCRIPTION_ID: "177add63-2747-4d6d-a5e4-004dc63b04c6"
-      ARM_TENANT_ID: "a55b816c-e99d-4af2-b69c-60fb4f03bef5"
+      # Steps represent a sequence of tasks that will be executed as part of the job
+      steps:
+        # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+        - uses: actions/checkout@v3
 
-    steps:
-      - uses: actions/checkout@v2
+        - name: Checkov GitHub Action
+          uses: bridgecrewio/checkov-action@v12
+          with:
+            # This will add both a CLI output to the console and create a results.sarif file
+            output_format: cli,sarif
+            output_file_path: console,results.sarif
+          
+        - name: Upload SARIF file
+          uses: github/codeql-action/upload-sarif@v3
+          
+          # Results are generated only on a success or failure
+          # this is required since GitHub by default won't run the next step
+          # when the previous one has failed. Security checks that do not pass will 'fail'.
+          # An alternative is to add `continue-on-error: true` to the previous step
+          # Or 'soft_fail: true' to checkov.
+          if: success() || failure()
+          with:
+            sarif_file: results.sarif
+  job2:
+    needs: job1
+    terraform:
+      runs-on: ubuntu-latest
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
+      env:
+        ARM_CLIENT_ID: "04684342-05fe-44a5-9c41-176278bf7fbd"
+        ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
+        ARM_SUBSCRIPTION_ID: "177add63-2747-4d6d-a5e4-004dc63b04c6"
+        ARM_TENANT_ID: "a55b816c-e99d-4af2-b69c-60fb4f03bef5"
 
-      - name: Terraform Init
-        run: terraform init
+      steps:
+        - uses: actions/checkout@v2
 
-      - name: Terraform Format
-        run: terraform fmt -check
+        - name: Setup Terraform
+          uses: hashicorp/setup-terraform@v1
 
-      - name: Terraform Plan
-        run: terraform plan
+        - name: Terraform Init
+          run: terraform init
+
+        - name: Terraform Format
+          run: terraform fmt -check
+
+        - name: Terraform Plan
+          run: terraform plan
